name: Deploy to Google Play

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Ensure Capacitor is initialized
        run: npx cap sync

      - name: Add Android platform
        run: npx cap add android

      - name: Copy web assets
        run: npx cap copy android

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android app
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Create Google Play service account JSON
        run: echo '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Upload APK to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account.json
          packageName: com.example.mathlectures
          releaseFile: android/app/build/outputs/apk/release/app-release.apk
          track: internal
